### ISSUE TITLE
Support default parameters in `case class` to `case class`

### ISSUE THREAD

**Issue by saeltz** [arainko/ducktape#38]
Given for example the following code:

```
final case class TestClass(str: String, int: Int)
final case class TestClassWithAdditionalList(int: Int, str: String, additionalArg: List[String] = Nil)
val testClass = TestClass("str", 1)
testClass.to[TestClassWithAdditionalList]
```

It will fail with `No field named 'additionalArg' found in TestClass`.

That's correct but `additionalArg` has a default parameter that could be used to fill that field. I could of course specify that manually but that's not the point of using ducktape at all, is it?

By the way: Thanks for your amazing work on this!
If you happen to point me to where and also maybe guide me how to implement it, I'd give it a try myself.
I'm currently exploring using ducktape to automatically create readers/writers for model classes and ScalaPB generated case classes to decouple internal and external models. In Protobuf there's almost always a default parameter.

**Comment by arainko** [comment]
Hey @saeltz! Yeah, default args is one of those 'oh yeah right they exist, I should probably support them somehow' but they also left a bitter taste after some unfortunate interactions while using `chimney` and generated models from `guardrail` (which generates defaults for `Options` and collections) - the problem was that my case classes didn't match the structure of the generated models which manifested in API responses with empty fields (even tho the code compiled).

I'd probably be in favor of using explicit opt-in configuration options to support defaults, like:

```scala
testClass.into[TestClassWithAdditionalList].transform(Field.fallbackToDefaults)
```
or something along those lines...
There's also the unfortunate and kinda hard to think about interaction with generics when working with macros (I might be wrong here tho, need to look more closely into this).

That being said, I'd also to gather some feedback on this, would an opt-in approach to defaults work for you?

**Comment by saeltz** [comment]
Hey @arainko,

I'm also for some kind of opt-in to using (specific) default values. In our case of using Protobuf it may happen that the producer adds some fields to an event that my service is consuming. At best, the compiler would tell me that there's a new field instead of just using the always-existent default value. Even better, the compiler would tell me how to use the default value if I'm not interested.
We can figure that out once we have a working draft.

I started working on this a little bit [in my fork](https://github.com/saeltz/ducktape/tree/defaultParams). Feel free to leave your thoughts. My goal is to get the test green in the most simple fashion and then extend with whatever we feel makes sense.

**Comment by arainko** [comment]
I've taken a look at your code and generally this:
```scala
// find dest fields that don't exist in source
    val surplusDestFields = Fields.dest.byName -- Fields.source.byName.keys
    println(surplusDestFields)
    // check those if they have default values
    val destFieldsWithDefault = surplusDestFields.values.foreach { field =>
      val tpr: TypeRepr = TypeRepr.of(using field.tpe)
      tpr.typeSymbol.flags.is(Flags.HasDefault)
    }
```
is sadly not that easy, to actually get information if a field has a default value you need to refer to its symbol inside the parent type (an example of this can be found here: https://github.com/lampepfl/dotty-macro-examples/blob/main/defaultParamsInference/src/macro.scala#L7 (this whole repo is a great source of information for dotty macros btw).

As for what would be needed to 'just' get the test working (and I mean in the most basic case, without generics etc.) you could try operating on `Option` inside `fieldTransformations` instead of aborting the macro:
```scala
private def fieldTransformations[Source: Type](
    sourceValue: Expr[Source],
    fieldsToTransformInto: List[Field]
  )(using Quotes, Fields.Source) = {
    import quotes.reflect.*

    fieldsToTransformInto.fmap { field => // flatMap here instead of map to get rid of Nones automatically
      field ->
        Fields.source
          .get(field.name)
          .getOrElse(Failure.abort(Failure.NoFieldMapping(field.name, Type.of[Source]))) // you'd get rid of this for a POC
    }.map { (dest, source) => 
      val call = resolveTransformation(sourceValue, source, dest)

      NamedArg(dest.name, call)
    }
  }
```

and then instead of doing `.getOrElse(Failure.abort(Failure.NoFieldMapping(field.name, Type.of[Source])))` you could flatten that list of options which would give you a `List[NamedArg]` which is then used to construct and instance of a case class here (part of the `ProductTransformations#transform)`:

```scala
constructor(TypeRepr.of[Dest])
      .appliedToArgs(transformerFields.toList)
      .asExprOf[Dest]
```

So now if you don't immediately fail with a NoFieldMapping but proceed to build the tree without all mappings, imagine your original example of:

```scala
final case class TestClass(str: String, int: Int)
final case class TestClassWithAdditionalList(int: Int, str: String, additionalArg: List[String] = Nil)
val testClass = TestClass("str", 1)
testClass.to[TestClassWithAdditionalList]
```

`.to[TestClassWithAdditionalList]` will roughly expand to:
```scala
new TestClassWithAdditionalList(int = testClass.int, str = testClass.str)
```
(note that we use named arguments here) and then the compiler will just happily insert the default value for you which SHOULD work for a basic proof of concept (I did not check if it actually does :(). Of course by doing that we kiss good errors goodbye and probably break some other things in the process.

**Comment by arainko** [comment]
Some great insights into pitfalls of defaults in chimney here: https://www.reddit.com/r/scala/comments/11b4ly0/chimney_070_released/

**Comment by saeltz** [comment]
Thanks! I tried what you suggested on my branch. It fails with the following error:
```
wrong number of arguments at pickler for (str: String, int: Int, additionalArg: List[String]): 
  Issue38Spec.this.TestClassWithAdditionalList: (Issue38Spec.this.TestClassWithAdditionalList#<init> : 
  (str: String, int: Int, additionalArg: List[String]): 
    Issue38Spec.this.TestClassWithAdditionalList
), expected: 3, found: 2
```

> Some great insights into pitfalls of defaults in chimney

That's why we built https://github.com/moia-oss/teleproto/ to work with ScalaPB. It works nicely but is a giant Scala 2 macro. I'm investigating if using ducktape would be a fit to solve the same problem. Opting in to using a default argument per field is definitely necessary.

**Comment by arainko** [comment]
> Thanks! I tried what you suggested on my branch. It fails with the following error:
> 
> ```
> wrong number of arguments at pickler for (str: String, int: Int, additionalArg: List[String]): 
>   Issue38Spec.this.TestClassWithAdditionalList: (Issue38Spec.this.TestClassWithAdditionalList#<init> : 
>   (str: String, int: Int, additionalArg: List[String]): 
>     Issue38Spec.this.TestClassWithAdditionalList
> ), expected: 3, found: 2
> ```
Ahh - it worked in my mental compiler tho! :smile: but yeah, I guess we don't get syntax-sugar niceties when we construct the trees by hand.

So the other way of making it work (once again I'm only theorizing) is putting a `hasDefault` field in `Field` which would be filled in during construction of `Fields` (eg. in `Fields.Source.fromMirror`) you'd need to the magic dance of inspecting the type symbol of the enclosing case class to determine if a given field actually has a default. Once you have that info you should be able to do some mucking around here:
```scala
private def fieldTransformations[Source: Type](
    sourceValue: Expr[Source],
    fieldsToTransformInto: List[Field]
  )(using Quotes, Fields.Source) = {
    import quotes.reflect.*

    fieldsToTransformInto.map { field =>
      field ->
        Fields.source
          .get(field.name)
          .getOrElse(Failure.abort(Failure.NoFieldMapping(field.name, Type.of[Source]))) // fail only if a field doesn't have a default?
    }.map { (dest, source) => 
      val call = resolveTransformation(sourceValue, source, dest) // resolveTransformation should then try to summon a Transformer or reference the default field

      NamedArg(dest.name, call)
    }
  }
```
as for actually materializing the values of default fields, these are encoded as (invisible to the user) methods in companions of a given case class, so once again more mucking around with symbols - https://github.com/lampepfl/dotty-macro-examples/blob/main/defaultParamsInference/src/macro.scala#L7

All of that for a PoC, to actually make it opt-in an configurable we'd need to think thru some designs, but I've got a rough idea if you're still on board :smile:

**Comment by saeltz** [comment]
> So the other way of making it work (once again I'm only theorizing) is putting a hasDefault field in Field which would be filled in during construction of Fields (eg. in Fields.Source.fromMirror) you'd need to the magic dance of inspecting the type symbol of the enclosing case class to determine if a given field actually has a default.

Extending `Field`'s constructor with a `val default: Option[?]` seems reasonable. The only problem I struggle with right now is that the macro for default parameters somehow only works when called inside the test but not when called from within anywhere of the inlined methods like `productTransformations`. The macro must be called from an `inline` method and if I inline the code of the macro, I get different, non-helpful output. Any ideas?

> but I've got a rough idea if you're still on board

Sure, I want to find a proper solution to this.

**Comment by arainko** [comment]
Let's see those errors then! 😄

**Comment by saeltz** [comment]
I pushed the code to my branch.
If I inline the macro code it yields:
```
Map(additionalArg -> Select(Select(This(Ident(Issue38Spec)),TestClassWithAdditionalList),$lessinit$greater$default$3))
```
I cannot call the `defaultParamImpl` because `productTransformation` is not an inline method.
If I call `defaultParam` I get something else that doesn't include the default value.
The same works fine in the test.

**Comment by saeltz** [comment]
It works now! Check out my branch. I also added configuration per field (which is what I find most ergonomic).

> I'm pretty worried about this, `Symbol#tree` has a warning slapped on it that it shouldn't be relied on without `-Yretain-trees`, wonder if there is another way of doing this

I just copied that from the dotty-macro-examples.

**Comment by arainko** [comment]
This looks phenomenal! Maybe you can create a PR out of it and we can bikeshed to our hearts content on that?

**Comment by saeltz** [comment]
Opened #39. Feel free to bikeshed. I'm not working the next two weeks. I'll address your feedback afterwards.
