### ISSUE TITLE
FallibleTransformer derivation for coproducts

### ISSUE THREAD

**Issue by gregor-i** [arainko/ducktape#67]
Hello,

I am currently trying to migrate an application from chimney to ducktape. 
The application uses `TransformerF` to validate an outer model towards an inner model.  The validation mostly checks for mandatory fields.

------

To demonstrate the issue, I created a minimal example:

```scala
type ErrorsOrResult = [X] =>> Either[List[String], X]

given Transformer.Mode.Accumulating[ErrorsOrResult] =
  Transformer.Mode.Accumulating.either[String, List]

implicit def deriveMandatoryOptionTransformer[A, B](
  implicit transformer: FallibleTransformer[ErrorsOrResult, A, B],
): FallibleTransformer[ErrorsOrResult, Option[A], B] = {
  case Some(a) => transformer.transform(a)
  case None => Left(List("Missing required field"))
}

sealed trait Outer
object Outer {
  case object Empty extends Outer
  final case class Element(cmd: Option[Int]) extends Outer
}

sealed trait Inner
object Inner {
  case object Empty extends Inner
  final case class Element(cmd: Int) extends Inner
}

```

Deriving FallibleTransformer for the `Element` case works fine:
```scala
implicitly[FallibleTransformer[ErrorsOrResult, Outer.Element, Inner.Element]]
```

But not for the sum type (`Inner` vs. `Outer`) and the `Empty` case:
```scala
implicitly[FallibleTransformer[ErrorsOrResult, Outer, Inner]]
implicitly[FallibleTransformer[ErrorsOrResult, Outer.Empty.type, Inner.Empty.type]]
```

---- 

Should this transformation / validation be supported? Is there something wrong with the way I am using the fallable transformers?

**Comment by arainko** [comment]
`FallibleTransformer` derivation is only supported for products at this time but you should be able to derive instances for all of the children and then create an encompassing FallibleTransformer for the whole coproduct (which I think is how it should be done automatically as well - I just haven't gotten around to implementing it yet due to lack of time)

**Comment by tim1bre** [comment]
Do you have a timeline for when you will work on this issue?

**Comment by arainko** [comment]
No clear timeline, I did land #61 just a week or so ago and I have my aims set on doing the same for fallible transformers - that's all I can say riggt now 😄

**Comment by gregor-i** [comment]
Thank you for the quick response!

Are you accepting contributions? If so, I would try to provide a PR for this issue.

**Comment by arainko** [comment]
Of course! I'm happy to give you some pointers - I'd start by looking at how total `Transformer` derivation for `Coproducts` is handled (`CoproductTransformations.scala`), this pretty much comes down to grouping the subtypes by name and then creating an if-else statement that does `.isInstanceOf` checks and summons `Transformer` instances for the corresponding types. I think we can get by just doing this for fallible transformations as well, except that instead of deriving `Transformers` we'll be asking for `FallibleTransformers`.

The other thing to think about are configuration options for fallible coproducts which should probably come in 2 flavors `Case.fallibleConst` and `Case.fallibleComputed` but I think that'd be a separate issue.

If you have any questions feel free to ask them here, I'll now go on to actually creating a CONTRIBUTING.md, hah.

**Comment by arainko** [comment]
A snapshot release is on its way to Maven Central as we speak - I'll cut a proper release once I get fallible config options for coproducts working. Once again, big thanks to @gregor-i  for stepping up :smile:
